#Data cleansing with pandas
**What is data cleansing?**</br>Data cleaning is the process of identiying and addresing problems that make data unreliable/difficult to analyse.
Common data cleaning problems include:
-missing values
-duplicate values
-incostitent values
-incorrect data types
-invalid values

An outlier which is unusully high or low value compared to the observation is not automatically an error. for example. if the patient wait time is normally between 10min to 15 min but there is arecord value of 50 min wait time, this is clearly an outlier but that does not mean its erroneous . we will end up deciding wether to drop or retain the values/outlier However, a negative age violates the meaning o the meaning of that column denoting that its erroneous.

**Data Cleansing Process**
-presreve the raw data and create a working copy.
-inspect the Data cleansing issues:missing values, duplicate values, erroneous values, column inconsistencies, null values e.t.c
-Deal with the issues example dropping null values, imputations, introduce uniormity e.t.c
-save the cleaaned copy.

In [4]:
#step 1 : Load Data
import pandas as pd
clinics_visits = pd.read_csv('clinic_visits_raw.csv')
clinics_visits.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

In [5]:
#step 2: Make a copy of the raw data
clinics_visits_copy = clinics_visits.copy()
clinics_visits_copy.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

***Data Cleaning Steps***
1.Checking for duplicates and missing values
2.Drop  duplicates and drop/inpute missing values
3.Check and handle outliers
4.Standardize column names
#

In [9]:
#step 3: Checking for data types of each column
clinics_visits_copy.dtypes

visit_id            str
patient_id          str
clinic_id           str
visit_date          str
age             float64
service             str
fee_kes             str
wait_minutes    float64
dtype: object

In [8]:
#step 4 :inspecting the data for null/missing values
clinics_visits_copy.isnull().sum()
#diff btwn isnull() and isna() is that isnull() is a method of pandas DataFrame and Series objects, while isna() is a method of pandas Series objects. Both methods return a boolean mask indicating the presence of missing values in the data.

visit_id        0
patient_id      0
clinic_id       0
visit_date      0
age             1
service         0
fee_kes         0
wait_minutes    1
dtype: int64

In [10]:
#step 5: Checking for duplicates
clinics_visits_copy.duplicated().sum()

np.int64(1)

In [12]:
#identify the duplicated row
duplicated_rows = clinics_visits_copy[clinics_visits_copy.duplicated(keep=False)]
duplicated_rows

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0
10,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0

In [29]:
#remove the duplicated row
drop_duplicates = clinics_visits_copy.drop_duplicates().reset_index(drop=True)
print(drop_duplicates)

   visit_id patient_id clinic_id    visit_date   age         service  fee_kes  \
0      V001        P01       C01    2026-01-05  24.0   consultation      1200
1      V002        P02       C02    2026-01-05  35.0             LAB      800
2      V003        P03       C01    2026-01-06   NaN    Consultation     1200
3      V004        P04       C03    2026-01-06  42.0        Pharmacy      500
4      V005        P05       C02    2026-02-03  29.0    consultation     1200
5      V006        P01       C01    2026-02-03  24.0             Lab      800
6      V007        P06       C03    2026-02-04  -5.0        Pharmacy      500
7      V008        P07       C02    2026-02-04  31.0   Consultation      1200
8      V009        P08       C01    2026-02-05  50.0             Lab  unknown
9      V010        P09       C03    2026-02-05  38.0        Pharmacy      500
10     V011        P10       C02  not-recorded  45.0             Lab      800
11     V012        P11       C03    2026-02-06  60.0    Consultation     1200

    wait_minutes
0           30.0
1           45.0
2           25.0
3           15.0
4            NaN
5           35.0
6           20.0
7           40.0
8           50.0
9           10.0
10          30.0
11          60.0

In [32]:
#step  5:standardize the columns (remove the white spaces and consistent naming )
clinics_visits_copy.columns = clinics_visits_copy.columns.str.strip().str.lower().str.replace(' ', '_')
clinics_visits_copy

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN
5,V006,P01,C01,2026-02-03,24.0,Lab,800,35.0
6,V007,P06,C03,2026-02-04,-5.0,Pharmacy,500,20.0
7,V008,P07,C02,2026-02-04,31.0,Consultation,1200,40.0
8,V009,P08,C01,2026-02-05,50.0,Lab,unknown,50.0
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0
10,V011,P10,C02,not-recorded,45.0,Lab,800,30.0
11,V012,P11,C03,2026-02-06,60.0,Consultation,1200,60.0

In [33]:
#step 6: convert data types for the following columns:fees(int) and data(datetime)
clinics_visits_copy["fee_kes"] = clinics_visits_copy["fee_kes"].astype(int)

clinics_visits_copy["visit_date"] = pd.to_datetime(
    clinics_visits_copy["visit_date"],
    format="%Y-%m-%d"
)

ValueError: invalid literal for int() with base 10: 'unknown'

In [ ]:
#step 7 : check for invalid ages and missing times

In [ ]:
#step 8 : choose between retaining , dropping and filling (imputing) the missing values

In [ ]:
#step 9: Validate the cleaned data and export it to a new CSV file
clinics_visits_copy.to_csv("cleaned_clinics_visits.csv", index=False)