In [15]:
import pandas as pd
#panda series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively referred to as the index. A pandas Series can be created from a list, dictionary, or scalar value.  
age = pd.Series([22, 34, 27, 44, 19], name='Age'        )
age

0    22
1    34
2    27
3    44
4    19
Name: Age, dtype: int64

In [16]:
#create a series that stores temprature
temperature = pd.Series([30, 32, 28, 35, 31], index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], name='Temperature')
temperature

Monday       30
Tuesday      32
Wednesday    28
Thursday     35
Friday       31
Name: Temperature, dtype: int64

In [ ]:
**Data frames**</br>are two-dimensional labeled data structures with columns of potentially different types. You can think of them like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

In [18]:
students = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [20, 21, 19, 22],
    'Country': ['America', 'Brazil', 'Canada', 'Australia']
}
print(students)
#turn it into a data frame
df = pd.DataFrame(students)
print(df)

{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [20, 21, 19, 22], 'Country': ['America', 'Brazil', 'Canada', 'Australia']}
      Name  Age    Country
0    Alice   20    America
1      Bob   21     Brazil
2  Charlie   19     Canada
3    David   22  Australia

In [32]:

#1 Reassign the indexes to 101, 102, 103, and 104.
df.index = [101, 102, 103, 104]
print(df)

    Student_Name  Age Home_Country
101        Alice   20      America
102          Bob   21       Brazil
103      Charlie   19       Canada
104        David   22    Australia

In [20]:
# disply the number of rows and columns 
df.shape

(4, 3)

In [21]:
#display the column names
df.columns

Index(['Name', 'Age', 'Country'], dtype='str')

In [22]:
#check the data types of each column
df.dtypes

Name         str
Age        int64
Country      str
dtype: object

In [23]:
#display the current index of the data frame
df.index

Index([101, 102, 103, 104], dtype='int64')

In [24]:
#select one column from the data frame
df['Name']

101      Alice
102        Bob
103    Charlie
104      David
Name: Name, dtype: str

In [25]:
#select two columns from the data frame
df[['Name', 'Age']]

        Name  Age
101    Alice   20
102      Bob   21
103  Charlie   19
104    David   22

In [33]:
#select a specific row from the data frame using the index label
df.loc[103]

Student_Name    Charlie
Age                  19
Home_Country     Canada
Name: 103, dtype: object

In [34]:
#display the third student using the row index position
df.iloc[2]

Student_Name    Charlie
Age                  19
Home_Country     Canada
Name: 103, dtype: object

In [28]:
#select the first two rows and columns of the data frame
df.iloc[0:2, 0:2]

      Name  Age
101  Alice   20
102    Bob   21

In [30]:
#Display the names and ages of the students who are older than 20.
df[df['Age'] > 20][['Name', 'Age']]

      Name  Age
102    Bob   21
104  David   22

In [31]:
#rename the column 'Name' to 'Student_Name' and 'Country' to 'Home_Country'
df.rename(columns={'Name': 'Student_Name', 'Country': 'Home_Country'}, inplace=True)