# DATA CLEANING WITH PANDAS
**what is data cleaning?**</br>Data cleaning is the process of identfying and addressing problems that makes data unreliable/difficult to analyse
comomon mistakes:
common data cleaning problems include:

-Inconsistent Text

-Incorrect value

-Invalid values



An outlier which is an unusually high or low value compared to the observation is not automatically an error. For example, if the patient wait time is normally between 10 mins to 25 mins but there is a recorded value of a 90 mins wait time, this is clearly an outlier but that does not mean its erroneous. We will end up deciding whether to drop or retain the value\outlier. However, if negative age value violates the meaning of that column denoting that is erroneous.

**Data Cleaning Process**
-Preserve the raw data and create a working copy

-Inspect the data cleaning issues:missing values,duplicate values,erroneus values, column inconsistences,null values etc

-Deal with the issues:dropping null values,imputations, introduce uniformity etc

-Saved the cleaned copy

In [1]:
#Step 1:Load Data
import pandas as pd
cleaning_visits = pd.read_csv("clinic_visits_raw.csv")
#preview data
cleaning_visits.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

In [2]:
#step 2: Make a copy of raw data
clinic_visits_copy=cleaning_visits.copy()
clinic_visits_copy.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

In [3]:
#step 3:

In [4]:
"""
Data cleaning steps:
1 check for Duplicate and missing ValueError
2.drop duplicate and drop/impute missing ValueError
3. check and handle outliers
4.check for data types
5. standardize column
"""
#step 3.: check for data tpes
print(clinic_visits_copy.dtypes)
#step 4: Inspect for null/ missing and duplicate values
print(clinic_visits_copy.isnull().sum())
print("\n\n")
print(clinic_visits_copy.isna().sum())
print("\n\n")
print(clinic_visits_copy.duplicated().sum())

#step 4:checking for duplicates

#The positive output values shows presence of null values hence cleaning is needed
#TO DO:Read on the difference of .isna and.isnull

visit_id            str
patient_id          str
clinic_id           str
visit_date          str
age             float64
service             str
fee_kes             str
wait_minutes    float64
dtype: object
visit_id        0
patient_id      0
clinic_id       0
visit_date      0
age             1
service         0
fee_kes         0
wait_minutes    1
dtype: int64



visit_id        0
patient_id      0
clinic_id       0
visit_date      0
age             1
service         0
fee_kes         0
wait_minutes    1
dtype: int64



1

In [5]:
print(clinic_visits_copy.duplicated().sum())

1

In [6]:
names=pd.DataFrame(
    {
     "name":["Diana","Alex","Alex","Ian"]
    }
)
names

    name
0  Diana
1   Alex
2   Alex
3    Ian

In [7]:
#identify the duplicates row
duplicate_rows=clinic_visits_copy[clinic_visits_copy.duplicated(keep=False)]
print(duplicate_rows)

   visit_id patient_id clinic_id  visit_date   age   service fee_kes  \
9      V010        P09       C03  2026-02-05  38.0  Pharmacy     500
10     V010        P09       C03  2026-02-05  38.0  Pharmacy     500

    wait_minutes
9           10.0
10          10.0

In [8]:
#remove the exact duplicates
clinic_visits_copy=clinic_visits_copy.drop_duplicates().reset_index(drop=True)
#.drop_duplicate():searches across the DataFrame and deletes identical rows
clinic_visits_copy

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN
5,V006,P01,C01,2026-02-03,24.0,Lab,800,35.0
6,V007,P06,C03,2026-02-04,-5.0,Pharmacy,500,20.0
7,V008,P07,C02,2026-02-04,31.0,Consultation,1200,40.0
8,V009,P08,C01,2026-02-05,50.0,Lab,unknown,50.0
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0
10,V011,P10,C02,not-recorded,45.0,Lab,800,30.0
11,V012,P11,C03,2026-02-06,60.0,Consultation,1200,60.0

In [9]:
# step 5: standardize the columns (remove white spaces and consistent naming)
clinic_visits_copy.columns=clinic_visits_copy.columns.str.strip().str.lower()
clinic_visits_copy

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN
5,V006,P01,C01,2026-02-03,24.0,Lab,800,35.0
6,V007,P06,C03,2026-02-04,-5.0,Pharmacy,500,20.0
7,V008,P07,C02,2026-02-04,31.0,Consultation,1200,40.0
8,V009,P08,C01,2026-02-05,50.0,Lab,unknown,50.0
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0
10,V011,P10,C02,not-recorded,45.0,Lab,800,30.0
11,V012,P11,C03,2026-02-06,60.0,Consultation,1200,60.0

In [10]:
#step 6: convert data types for the following columns: fees(int) and dates (datetime)

clinic_visits_copy['visit_date'] = pd.to_datetime(
    clinic_visits_copy['visit_date'], 
    errors='coerce', 
    format='mixed'
)

# 2. Clean fee_kes (remove currency symbols/commas/text) and convert to numeric
clinic_visits_copy['fee_kes'] = (
    clinic_visits_copy['fee_kes']
    .astype(str)
    .str.replace(r'[^\d.]', '', regex=True)
)
clinic_visits_copy['fee_kes'] = pd.to_numeric(clinic_visits_copy['fee_kes'], errors='coerce')
clinic_visits_copy

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200.0,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800.0,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200.0,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500.0,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200.0,NaN
5,V006,P01,C01,2026-02-03,24.0,Lab,800.0,35.0
6,V007,P06,C03,2026-02-04,-5.0,Pharmacy,500.0,20.0
7,V008,P07,C02,2026-02-04,31.0,Consultation,1200.0,40.0
8,V009,P08,C01,2026-02-05,50.0,Lab,NaN,50.0
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500.0,10.0
10,V011,P10,C02,NaT,45.0,Lab,800.0,30.0
11,V012,P11,C03,2026-02-06,60.0,Consultation,1200.0,60.0

In [11]:
# convert data types for the following rows: fees(int) and dates (datetime)


# 1. Convert visit_date to datetime
clinic_visits_copy['visit_date'] = pd.to_datetime(
    clinic_visits_copy['visit_date'], 
    errors='coerce', 
    format='mixed'
)

# 2. Clean fee_kes (remove symbols, text, decimals) and convert to integer
clinic_visits_copy['fee_kes'] = (
    clinic_visits_copy['fee_kes']
    .astype(str)
    .str.replace(r'[^\d.]', '', regex=True)  # Remove currency symbols/commas
)

# Convert to float first (to handle decimals like 1200.0), then to integer
clinic_visits_copy['fee_kes'] = (
    pd.to_numeric(clinic_visits_copy['fee_kes'], errors='coerce')
    .fillna(0)             # Or dropna/impute before integer conversion if needed
    .astype('int64')
)

# Verify updated datatypes
print(clinic_visits_copy[['visit_date', 'fee_kes']].dtypes)

visit_date    datetime64[us]
fee_kes                int64
dtype: object

In [12]:
#step 7 : check the invalid ages and missing times


# 1. Check for invalid age values (negative ages or unrealistic ages over 120)
invalid_ages = clinic_visits_copy[
    (clinic_visits_copy['age'] < 0) | (clinic_visits_copy['age'] > 120)
]

print(invalid_ages[['visit_id', 'patient_id', 'age']])


# 2. Check for missing (null) values in wait_minutes
missing_wait_times = clinic_visits_copy[clinic_visits_copy['wait_minutes'].isnull()]

print(missing_wait_times[['visit_id', 'patient_id', 'wait_minutes']])


# 3. Check for invalid (negative) wait times
invalid_wait_times = clinic_visits_copy[clinic_visits_copy['wait_minutes'] < 0]

print(invalid_wait_times[['visit_id', 'patient_id', 'wait_minutes']])


# 4. Check for extreme wait time outliers using IQR (Interquartile Range)
Q1 = clinic_visits_copy['wait_minutes'].quantile(0.25)
Q3 = clinic_visits_copy['wait_minutes'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outlier_wait_times = clinic_visits_copy[clinic_visits_copy['wait_minutes'] > upper_bound]

print(outlier_wait_times[['visit_id', 'service', 'wait_minutes']])

  visit_id patient_id  age
6     V007        P06 -5.0
  visit_id patient_id  wait_minutes
4     V005        P05           NaN
Empty DataFrame
Columns: [visit_id, patient_id, wait_minutes]
Index: []
Empty DataFrame
Columns: [visit_id, service, wait_minutes]
Index: []

"""
# Step 8: Handling Invalid, Missing, and Extreme Values

After identifying data-quality problems, we need to decide how to handle each
problem appropriately. The three main approaches are imputing, retaining, and
dropping values.

# 1. IMPUTING MISSING VALUES

When a value is missing, we can sometimes estimate a reasonable replacement
instead of deleting the entire record.

For missing wait times, we calculate the median wait time and use it to fill
the missing values.

The median is the middle value when all observations are arranged from
smallest to largest. It is useful for wait times because it is less affected
by extremely long waiting times than the mean.

For example, if the wait times are:

    10, 12, 15, 20, 25, 100

The value 100 is unusually high and could pull the average upward. The median
gives a better representation of a typical waiting time.

We therefore use:

    median_wait = clinic_visits_copy['wait_minutes'].median()

and then fill missing wait times using:

    clinic_visits_copy['wait_minutes'].fillna(median_wait)

This allows us to keep the patient record while providing a reasonable value
for the missing wait time.


# 2. IDENTIFYING EXTREME WAIT TIMES USING THE INTERQUARTILE RANGE (IQR)

Before deciding whether an unusually high wait time should be removed, we
first need to determine whether it is an extreme value.

The Interquartile Range (IQR) measures the spread of the middle 50% of the
data.

First, we calculate:

    Q1 = 25th percentile
    Q3 = 75th percentile

Then:

    IQR = Q3 - Q1

The upper boundary for potential outliers is calculated as:

    Upper Bound = Q3 + (1.5 × IQR)

Any wait time above this boundary is considered a potential outlier.

It is important to remember that an outlier is not automatically an error.
For example, a patient may genuinely have waited several hours. Therefore,
extreme wait times should be investigated before deciding whether to remove
them.

If an extreme value is legitimate, we RETAIN it.


# 3. DROPPING INVALID VALUES

Some values are clearly invalid and cannot reasonably be used.

For example:

    age = -5
    wait_minutes = -10

A negative age or negative waiting time does not make logical sense.

If the correct value cannot be determined from another reliable source, the
affected record can be removed from the dataset.

For example, we can keep only ages between 0 and 120 and only non-negative
wait times.

Dropping should be used carefully because removing records reduces the amount
of available data.


# 4. RETAINING VALID BUT UNUSUAL VALUES

Not every unusual value should be removed.

If an outlier is unusual but represents a real observation, we retain it.

For example, if a patient genuinely waited 150 minutes, the value may be an
outlier but it is not necessarily incorrect.

The goal of data cleaning is not to make every value look normal. The goal is
to make the dataset accurate and reliable while preserving legitimate
information.


# OVERALL DECISION PROCESS

The cleaning process can therefore be summarized as:

    Missing value
        ↓
    Can it be reasonably estimated?
        ↓
    Yes → Impute using an appropriate value such as the median

    Invalid value
        ↓
    Can the correct value be determined?
        ↓
    No → Drop the affected record

    Unusual/extreme value
        ↓
    Is it a genuine observation?
        ↓
    Yes → Retain it
    No  → Remove or correct it

The main principle is to choose the treatment based on the nature of the
problem rather than automatically deleting unusual or missing data.
"""

In [13]:

#  INVALID VALUES & IMPUTATION


# 1. Fix negative values in ID columns (patient_id, visit_id, clinic_id)
id_cols = [col for col in ['patient_id', 'visit_id', 'clinic_id'] if col in clinic_visits_copy.columns]
for col in id_cols:
    clinic_visits_copy[col] = clinic_visits_copy[col].astype(str).str.replace('-', '', regex=False)

# 2. Impute missing visit_date (e.g., P10 / V011) using forward-fill
clinic_visits_copy['visit_date'] = clinic_visits_copy['visit_date'].ffill()

# 3. Handle invalid Age values (< 0 or > 120)
invalid_age_mask = (clinic_visits_copy['age'] < 0) | (clinic_visits_copy['age'] > 120)
clinic_visits_copy.loc[invalid_age_mask, 'age'] = pd.NA

median_age = clinic_visits_copy['age'].median()
clinic_visits_copy['age'] = clinic_visits_copy['age'].fillna(median_age)

# 4. Handle invalid negative Wait Times
clinic_visits_copy.loc[clinic_visits_copy['wait_minutes'] < 0, 'wait_minutes'] = pd.NA

# 5. Impute missing/invalid Wait Times by service category
clinic_visits_copy['wait_minutes'] = clinic_visits_copy.groupby('service')['wait_minutes'].transform(
    lambda x: x.fillna(x.median())
)
clinic_visits_copy['wait_minutes'] = clinic_visits_copy['wait_minutes'].fillna(
    clinic_visits_copy['wait_minutes'].median()
)

# 6. Handle fee_kes missing values
if 'fee_kes' in clinic_visits_copy.columns:
    clinic_visits_copy['fee_kes'] = clinic_visits_copy.groupby('service')['fee_kes'].transform(
        lambda x: x.fillna(x.median())
    )

In [14]:
#step 9:validate the cleaned Data and export(save) it as a CSV file

# 1. Inspect data structure and data types

print(clinic_visits_copy.info())

# 2. Verify zero remaining missing (null) values

print(clinic_visits_copy.isnull().sum())

# 3. Verify zero remaining duplicate rows

print(f"Duplicate row count: {clinic_visits_copy.duplicated().sum()}")

# 4. Statistical summary to confirm ranges (age, fee_kes, wait_minutes)

print(clinic_visits_copy.describe())

# 5. Preview first few clean records

print(clinic_visits_copy.head())


# EXPORT TO CSV


output_filename = "clinic_visits_cleaned.csv"
clinic_visits_copy.to_csv(output_filename, index=False)

print(f"\n Validation complete! Cleaned dataset successfully saved as '{output_filename}'.")

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   visit_id      12 non-null     str
 1   patient_id    12 non-null     str
 2   clinic_id     12 non-null     str
 3   visit_date    12 non-null     datetime64[us]
 4   age           12 non-null     float64
 5   service       12 non-null     str
 6   fee_kes       12 non-null     int64
 7   wait_minutes  12 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 900.0 bytes
None
visit_id        0
patient_id      0
clinic_id       0
visit_date      0
age             0
service         0
fee_kes         0
wait_minutes    0
dtype: int64
Duplicate row count: 0
                visit_date        age      fee_kes  wait_minutes
count                   12  12.000000    12.000000     12.000000
mean   2026-01-25 10:00:00  37.583333   825.000000     32.500000
min    2026-01-05 00:00:00  24.000000     0.000000     10.000000
25%    2026-01-06 00:00:00  30.500000   500.000000     23.750000
50%    2026-02-03 12:00:00  36.500000   800.000000     30.000000
75%    2026-02-05 00:00:00  42.750000  1200.000000     41.250000
max    2026-02-06 00:00:00  60.000000  1200.000000     60.000000
std                    NaN  10.558997   393.411651     14.538351
  visit_id patient_id clinic_id visit_date   age         service  fee_kes  \
0     V001        P01       C01 2026-01-05  24.0   consultation      1200
1     V002        P02       C02 2026-01-05  35.0             LAB      800
2     V003        P03       C01 2026-01-06  36.5    Consultation     1200
3     V004        P04       C03 2026-01-06  42.0        Pharmacy      500
4     V005        P05       C02 2026-02-03  29.0    consultation     1200

   wait_minutes
0          30.0
1          45.0
2          25.0
3          15.0
4          30.0

 Validation complete! Cleaned dataset successfully saved as 'clinic_visits_cleaned.csv'.

In [15]:
clinic_visits_copy

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,36.5,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,30.0
5,V006,P01,C01,2026-02-03,24.0,Lab,800,35.0
6,V007,P06,C03,2026-02-04,36.5,Pharmacy,500,20.0
7,V008,P07,C02,2026-02-04,31.0,Consultation,1200,40.0
8,V009,P08,C01,2026-02-05,50.0,Lab,0,50.0
9,V010,P09,C03,2026-02-05,38.0,Pharmacy,500,10.0
10,V011,P10,C02,2026-02-05,45.0,Lab,800,30.0
11,V012,P11,C03,2026-02-06,60.0,Consultation,1200,60.0